AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for AI Transcription Application'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access
  
  DBPassword:
    Type: String
    NoEcho: true
    Description: MongoDB password
    MinLength: 8

Resources:
  # VPC Configuration
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: TranscriptionVPC

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: TranscriptionIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnet (WebApp)
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet

  # Private Subnet (Database)
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet

  # Route Tables
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Groups
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for WebApp EC2
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: WebAppSG

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MongoDB EC2
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
      Tags:
        - Key: Name
          Value: DBSG

  # S3 Bucket for audio files
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'transcription-audio-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'

  # IAM Role for EC2 instances
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: TranscriptionAppPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !GetAtt AudioBucket.Arn
                  - !Sub '${AudioBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - transcribe:ListTranscriptionJobs
                  - transcribe:DeleteTranscriptionJob
                  - transcribe:StartStreamTranscription
                Resource: '*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # Database EC2 Instance
  DBInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId:  ami-02013548285198fde
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref DBSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          
          # Install MongoDB
          cat > /etc/yum.repos.d/mongodb-org-7.0.repo <<EOF
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc
          EOF
          
          yum install -y mongodb-org
          
          # Configure MongoDB
          sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
          echo 'security:' >> /etc/mongod.conf
          echo '  authorization: enabled' >> /etc/mongod.conf
          # Start MongoDB
          systemctl start mongod
          systemctl enable mongod
          
          # Create database and user
          mongosh <<MONGOEOF
          use transcription_db
          db.createUser({
            user: "transcriptionuser",
            pwd: "${DBPassword}",
            roles: [{role: "readWrite", db: "transcription_db"}]
          })
          MONGOEOF
      Tags:
        - Key: Name
          Value: MongoDB-Instance

  # WebApp EC2 Instance
  WebAppInstance:
    Type: AWS::EC2::Instance
    DependsOn: DBInstance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId:  ami-0483d83614cc6d061
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          
          # Install Node.js 18
          curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs git
          
          # Install PM2
          npm install -g pm2
          
          # Install Nginx
          yum install -y nginx
          systemctl start nginx
          systemctl enable nginx
          
          # Install CloudWatch Agent
          wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
          rpm -U ./amazon-cloudwatch-agent.rpm
          
          # Configure CloudWatch Agent
          cat > /opt/aws/amazon-cloudwatch-agent/etc/config.json <<'CWEOF'
          {
            "metrics": {
              "namespace": "TranscriptionApp",
              "metrics_collected": {
                "cpu": {
                  "measurement": [{"name": "cpu_usage_idle", "rename": "CPU_IDLE", "unit": "Percent"}],
                  "metrics_collection_interval": 60,
                  "totalcpu": false
                },
                "disk": {
                  "measurement": [{"name": "used_percent", "rename": "DISK_USED", "unit": "Percent"}],
                  "metrics_collection_interval": 60,
                  "resources": ["*"]
                },
                "mem": {
                  "measurement": [{"name": "mem_used_percent", "rename": "MEM_USED", "unit": "Percent"}],
                  "metrics_collection_interval": 60
                }
              }
            },
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/application.log",
                      "log_group_name": "/aws/ec2/transcription-app",
                      "log_stream_name": "{instance_id}"
                    }
                  ]
                }
              }
            }
          }
          CWEOF
          
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
            -a fetch-config \
            -m ec2 \
            -s \
            -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json
          
          # Create app directory
          mkdir -p /home/ec2-user/app
          chown ec2-user:ec2-user /home/ec2-user/app
          
          # Create environment file
          cat > /home/ec2-user/app/.env <<EOF
          PORT=5000
          MONGODB_URI=mongodb://transcriptionuser:${DBPassword}@${DBInstance.PrivateIp}:27017/transcription_db
          AWS_REGION=${AWS::Region}
          S3_BUCKET=${AudioBucket}
          NODE_ENV=production
          EOF
          
          chown ec2-user:ec2-user /home/ec2-user/app/.env
      Tags:
        - Key: Name
          Value: WebApp-Instance

  # SNS Topic for alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Transcription App Alerts
      TopicName: TranscriptionAppAlerts

  # CloudWatch Alarms
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: WebApp-High-CPU
      AlarmDescription: Alert when CPU exceeds 80%
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref WebAppInstance
      AlarmActions:
        - !Ref AlertTopic

  LowDiskSpaceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: WebApp-Low-Disk-Space
      AlarmDescription: Alert when disk usage exceeds 85%
      MetricName: DISK_USED
      Namespace: TranscriptionApp
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref WebAppInstance
      AlarmActions:
        - !Ref AlertTopic

Outputs:
  WebAppPublicIP:
    Description: Public IP of WebApp instance
    Value: !GetAtt WebAppInstance.PublicIp
    Export:
      Name: WebAppPublicIP

  WebAppURL:
    Description: URL of the web application
    Value: !Sub 'http://${WebAppInstance.PublicIp}'

  DBPrivateIP:
    Description: Private IP of MongoDB instance
    Value: !GetAtt DBInstance.PrivateIp
    Export:
      Name: DBPrivateIP

  S3BucketName:
    Description: Name of the S3 bucket for audio files
    Value: !Ref AudioBucket
    Export:
      Name: AudioBucketName

  SNSTopicArn:
    Description: ARN of SNS topic for alerts
    Value: !Ref AlertTopic
    Export:
      Name: AlertTopicArn